""""

This script is created to take images from the folder and resize them

"""

import cv2
import glob

#First we select a folder containing images and choose width and height in desired size. 25x25 is the recommended size.

filename = './'+input('output folder directory\n')+'/'+input("output file name\n")
input_file_directory='./'+input("input file directory\n")+"/**/*"
extension=input("image extension")
width=input("width")
height=input("height")
input_file_directory+=extension
counter = 0
params = " 1 0 0 "+str(width)+" "+str(height)

#Now we open a info.lst file created before
#info.lst specifies the location of the positive annotation file generated by the command

with open('info.lst', 'w') as info_file:

    for img in glob.glob(input_file_directory,recursive=True):

        image = cv2.imread(img)
        resized_image = cv2.resize(image,(int(width),int(height)),interpolation=cv2.INTER_AREA)
        #Since cv2 uses grayscale, we change the color of all specified images.
        resized_image=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
        final_file_name = filename+  str(counter)+"."+extension     # New file name.
        cv2.imwrite(final_file_name,resized_image)                  # Writing it to new folder.
        counter+=1      # For the next img
        info_file.write(final_file_name + params +'\n')

    info_file.close()